### ISSUE TITLE
Latest version does not search torrents?

### ISSUE THREAD

**Issue by Superiore-144** [mmgoodnow/cross-seed#174]
So,

**2.8.0**: Does actually search for torrents but the ```excludeOlder``` ```excludeRecentSearch``` does not work, i.e it searches everything everytime.

**2.9.0**: Does not give any results when searching, ```excludeOlder``` ```excludeRecentSearch``` seems to be working.

**2.9.1** Same as the 2.9.0, does not give any results when searching, ```excludeOlder``` ```excludeRecentSearch``` seems to be working.

I dont know if my issues are new, or if you already know about this. Please let me know if you need any verbose output or something.

Running Node.js v14.16.1 on Windows server 2016.

**Comment by mmgoodnow** [comment]
Do you use `trackers: []`? There was a related bug in 2.9.0. This has been fixed as of the latest version, 3.0.2

**Comment by Superiore-144** [comment]
Yes, but i did try to manually add some of the trackers but that didnt help.

I see that you have been busy the last few days, i did not notice that you have released new version! I'll check them out right away.

**Comment by Superiore-144** [comment]
Did an uninstall of cross-seed via npm. Reinstalled it and got this error.
After i got the error i also upgraded node.js to the latest version 17.3.0 and still the same error.

```
C:\Users\Administrator>cross-seed search
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:371:5)
    at defaultResolve (node:internal/modules/esm/resolve:1032:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ESMLoader.import (node:internal/modules/esm/loader:332:22)
    at importModuleDynamically (node:internal/modules/esm/translators:106:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at getFileConfig (file:///C:/Users/Administrator/AppData/Roaming/npm/node_modules/cross-seed/dist/configuration.js:31:9)
    at file:///C:/Users/Administrator/AppData/Roaming/npm/node_modules/cross-seed/dist/cmd.js:34:26
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}

Node.js v17.3.0
```

**Comment by mmgoodnow** [comment]
Ah the elusive windows user. I'll look into  that bug today

**Comment by Superiore-144** [comment]
> Ah the elusive windows user. I'll look into that bug today

Thanks!

**Comment by mmgoodnow** [comment]
Please reopen if it still doesn't find any results! Verbose logs would be helpful
