### ISSUE TITLE
Cache corruption

### ISSUE THREAD

**Issue by rj-d2** [mmgoodnow/cross-seed#69]
hi,

normaly i use this command
`cross-seed search --exclude-older 1440
`
this is my config.js

```
module.exports = {
	configVersion: 1,

	jackettServerUrl: "url",
	jackettApiKey: "api",
	delay: 5,
	trackers: ["trackers"],
	torrentDir: ".../rtorrent/session",
	outputDir: ".../.cross-seed/import",
	includeEpisodes: true,
	searchAll: true,

};
```

this usually works great as it just searches torrents which were added the last 24 hours.

i discovered that sometimes the --exclude-older flag is not working for me.
atm when i run the command i see this:

```
Validating your configuration...
Your configuration is valid!
Found 933 torrents, 473 suitable to search for matches
[1/473] Searching for ...
```

i was expecting to search 2 torrents which i added an hour ago, other than the 2 torrent there were no torrents added to rtorrent in the last 48 hours,
why is cross-seed searching all my torrent?

this happened to me a few times before, the next day when i run the command everything works as expected again.

any idea what could cause this?

edit:
when i use  --exclude-older 120

```
cross-seed search --exclude-older 120
Validating your configuration...
Your configuration is valid!
Found 933 torrents, 2 suitable to search for matches
[1/2] Searching for ...
```

it works fine

**Comment by mmgoodnow** [comment]
Sounds like your cache is getting deleted somehow. Do you use docker?

**Comment by mmgoodnow** [comment]
That firstSearched represents the number of milliseconds since Jan 1 1970 00:00 UTC. These numbers are called Unix timestamps. 

It would be possible to run cross-seed on your NAS but it works better on the same machine, especially if you're doing direct injection into rtorrent.

Do you run cross-seed automatically or manually? If manually, then I recommend just checking that the cache file exists before you run it, because that still seems like the most likely culprit to me.

**Comment by mmgoodnow** [comment]
You can also put excludeOlder into your config file btw.

**Comment by mmgoodnow** [comment]
Any updates here?

**Comment by solongandthxforallthefish** [comment]
Hi,
i deleted my cache and kept an eye on it, so far everything is fine.

must have been something on my end,
thx for your help

**Comment by DuzAwe** [comment]
So I seem to have this issue now. I have     excludeRecentSearch: 1440,  excludeOlder: 10080, in my config and they are not being read when I check the verbose output and when I use them as options on the command only -r is working.

**Comment by DuzAwe** [comment]
Should note this is a fresh install on a new RasPi image, but still cleared the cache to be safe

**Comment by mmgoodnow** [comment]
I have fixed the bug where it wasn't reading from the config file; will check out the -x flag specifically not working.

**Comment by str0ke-milw0rm** [comment]
Seems to be still an issue with 2.9.1 & 2.8.0.  If we can get the -x / exclude to work with the timestamp on the actual torrent, that would solve this problem imo.

**Comment by mmgoodnow** [comment]
I just tested it, --exclude-older functionality works as I expect (easy way to test is to clear the cache, run a small search, then wait a few minutes and try with `-x 1` and then `-x 10` and in the former case, nothing should run, but in the latter case, they should run.

If someone has a reliable way to reproduce this bug, then I might be able to solve it. Without a reliable repro however, there's not much I can do.

**Comment by key-str0ke** [comment]
I haven’t updated to the latest release yet, but previous versions would do
this if you kill the process “kill -9”.  Usually one of those, oh crap the
cronjob fired off and I don’t want to cross seed 50 new torrents before
they finish downloading.

To get around this.  I just copy new torrents by creation time to a
separate folder, cross-seed the separate folder, and then delete anything
over a certain time while utilizing the -x flag.  If something goes wrong
with cache, it minimizes any future issues.

**Comment by KnifeFed** [comment]
With the latest release, my cache was deleted again and it started searching for ~1000 torrents.

**Comment by mmgoodnow** [comment]
@KnifeFed 3.0.0 or 3.0.1? I went through a bit of a refactor upgrading lowdb and caught a bug in 3.0.0 this morning, which should be fixed in 3.0.1

**Comment by KnifeFed** [comment]
@mmgoodnow it happened 2021-12-29 02:05 CET when my containers auto-updated, so I guess that was 3.0.0?

**Comment by mmgoodnow** [comment]
yeah that would be 3.0.0. I recommend updating to 3.0.1 asap

**Comment by mmgoodnow** [comment]
https://github.com/mmgoodnow/cross-seed/issues/181#issuecomment-1003636148

Those of you that have experienced this bug with the cache getting corrupted/deleted - how large does your cache tend to grow?

**Comment by key-str0ke** [comment]
Currently what I am sitting at under ~/.cross-seed

5.1M cache.json
788M logs
 35M torrent_cache

**Comment by KnifeFed** [comment]
<img width="461" alt="Screen Shot 2022-01-02 at 15 36 12" src="https://user-images.githubusercontent.com/85502276/147879400-540fd7a5-1170-48a9-837f-9f7a7ec0326b.png">

**Comment by Jerrk** [comment]
i also seem to have this issue, `excludeRecentSearch: 43200` in the config but every day it tries to search for 1500~ torrents even if they were searched for the day before.
running docker daemon mode and calling the search with `docker exec cross-seed cross-seed search`
![](https://i.imgur.com/6zgtozU.png)

**Comment by mmgoodnow** [comment]
@Jerrk @KnifeFed @DuzAwe @rj-d2 @key-str0ke I believe I have a fix for this issue. I never fully uncovered what was happening but I suspect one cause was the program being stopped while it was writing the cache file.

Either way, I've been working on a much more robust data persistence layer backed by SQLite. This should alleviate the issue.

 if you get the chance, please try out the `sqlite` branch, either with the `sqlite` docker tag, or by cloning the repo, checking out the branch, and using `npm link && npm link cross-seed`. It should
- automatically migrate your data from `cache.json` to `cross-seed.db`
- if successful, rename `cache.json` to `old-cache.json.bak`
- run as normal

Please report any bugs if you find them.

**Comment by Jerrk** [comment]
one of my unraid servers is on rc4 and for some reason the cross-seed docker will not run on that machine at all.

And on my 6.9.2 machine the sqlite branch runs but there seems to be an issue during the configuration of the database
```
Configuration file already exists.
migration file "00-initialSchema" failed
migration failed with error: insert into `searchee` .......... [Dual Aud
/usr/src/app/node_modules/better-sqlite3/lib/methods/wrappers.js:5
return this[cppdb].prepare(sql, this, false);
^
SqliteError: insert into `searchee` ............. - too many terms in compound SELECT
at Database.prepare (/usr/src/app/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
at Client_BetterSQLite3._query (/usr/src/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:30:34)
at executeQuery (/usr/src/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
at Client_BetterSQLite3.query (/usr/src/app/node_modules/knex/lib/client.js:146:12)
at /usr/src/app/node_modules/knex/lib/execution/transaction.js:363:24
at new Promise (<anonymous>)
at Client_BetterSQLite3.trxClient.query (/usr/src/app/node_modules/knex/lib/execution/transaction.js:358:12)
at Runner.query (/usr/src/app/node_modules/knex/lib/execution/runner.js:130:36)
at ensureConnectionCallback (/usr/src/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
at Runner.ensureConnection (/usr/src/app/node_modules/knex/lib/execution/runner.js:307:20) {
code: 'SQLITE_ERROR'
}
```

the ellipses are all(?) of my torrents in a line

line 3 the line ends abruptly with [Dual Aud not sure what the issue would be here since in the config.json i do not have this error on that torrent.

**Comment by Jerrk** [comment]
new error

```
Configuration file already exists.
migration file "00-initialSchema" failed
migration failed with error: Cannot read property 'id' of undefined
file:///usr/src/app/dist/migrations/00-initialSchema.js:40
searchee_id: dbSearchees.find((searchee) => searchee.name === searcheeName).id,
^

TypeError: Cannot read property 'id' of undefined
at file:///usr/src/app/dist/migrations/00-initialSchema.js:40:96
at Array.map (<anonymous>)
at file:///usr/src/app/dist/migrations/00-initialSchema.js:38:44
at Array.map (<anonymous>)
at file:///usr/src/app/dist/migrations/00-initialSchema.js:37:14
```

**Comment by Jerrk** [comment]
tried on my other server as well (unraid rc-5), got similar error to the first attempt

```
Configuration file already exists.
migration file "00-initialSchema" failed
migration failed with error: insert into ... - UNIQUE constraint failed: decision.guid

/usr/src/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:39
    const response = await statement.run(bindings);
                                     ^
SqliteError: insert into ... - UNIQUE constraint failed: decision.guid
    at Client_BetterSQLite3._query (/usr/src/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:39:38)
    at executeQuery (/usr/src/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_BetterSQLite3.query (/usr/src/app/node_modules/knex/lib/client.js:146:12)
    at /usr/src/app/node_modules/knex/lib/execution/transaction.js:363:24
    at new Promise (<anonymous>)
    at Client_BetterSQLite3.trxClient.query (/usr/src/app/node_modules/knex/lib/execution/transaction.js:358:12)
    at Runner.query (/usr/src/app/node_modules/knex/lib/execution/runner.js:130:36)
    at ensureConnectionCallback (/usr/src/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/usr/src/app/node_modules/knex/lib/execution/runner.js:307:20)
    at async Runner.run (/usr/src/app/node_modules/knex/lib/execution/runner.js:30:19) {
  code: 'SQLITE_CONSTRAINT_UNIQUE'
}
```
the ellipses are all my torrents in one line.
